#!/usr/bin/zsh

__select_available() {
  paru --query --explicit --color always \
    | fzf \
      --multi \
      --ansi \
      --with-nth 1 \
      --preview 'paru --sync --info --info {1}' \
      --preview-window="$FZF_DEFAULT_PREVIEW_WINDOW_OPTS" \
    | awk '{print $1}'
}

parm() {
  local selection=$(__select_available)
  local args="$@"
  [[ $# == 0 ]] && args='--remove'

  if [ -n "$selection" ]; then
    local packages=("${(@f)$(echo $selection)}")
    local cmd="paru $args ${packages[@]}"
    # echo "$cmd"
    print -s "$cmd"
    eval "$cmd"
  fi
}

parm
