# Arch

spacing         = 2
padding         = 2
hide_ascii      = false
prefer_small_ascii = true
separator       = ""
key_color       = "Blue"
separator_color = "White"

[palette]
type = "Full"
visible = false

[bar]
glyph           = "ߋ"
symbol_open     = '['
symbol_close    = ']'
hide_delimiters = true
visible         = false

[box]
border          = "plain"
visible         = false

[box.inner_margin]
x               = 1
y               = 0

[randomize]
key_color       = false
separator_color = false

[custom_ascii]
color = "Blue"
path = "~/.config/macchina/themes/Arch.ascii"

[keys]
host            = ""
kernel          = ""
battery         = ""
os              = "OS"
de              = "拓"
wm              = ""
distro          = "" #  ﲎ
terminal        = ""
shell           = ""
packages        = ""
uptime          = ""
memory          = ""
machine         = "" # 
local_ip        = ""
backlight       = ""
resolution      = ""
cpu_load        = ""
cpu             = ""
