spacing = 1
padding = 1
hide_ascii = false
separator = ""
key_color = "Yellow"
separator_color = "Cyan"

[palette]
visible = false

[bar]
visible = false

[box]
visible = true
border = "rounded"
title = "─  Spica "

[box.inner_margin]
x = 1
y = 0

[randomize]
key_color = false
separator_color = false

[custom_ascii]
color = "Yellow"
path = "~/.config/macchina/themes/spica_ascii"

[keys]
host = "Host"
kernel = ""
battery = "Battery"
os = "OS"
de = "DE"
wm = "WM"
distro = "Distro"
terminal = "Terminal"
shell = "Shell"
packages = "Packages"
uptime = ""
memory = ""
machine = "Machine"
local_ip = "ﯱ"
backlight = "Brightness"
resolution = "Resolution"
cpu_load = ""
cpu = "CPU"
