# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["micro", "containers"]

display_preamble = false

# Run inside tmux
run_in_tmux = false

[git]
max_concurrency = 5
# Additional git repositories to pull
repos = [
    "~/Projects/*/"
]
# Arguments to pass Git when pulling Repositories
arguments = "--recurse-submodules"

# Commands to run before anything
[pre_commands]
#"Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Custom commands
[commands]
#"Python Environment" = "~/dev/.env/bin/pip install -i https://pypi.python.org/simple -U --upgrade-strategy eager jupyter"
